services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:4000
    volumes:
      - ./app/public:/app/public
    networks:
      - network_sistema_todo

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - servidor-ca
      - mongo
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development  
      - CA_HOST=servidor-ca
      - CA_PORT=5000
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - HMAC_SECRET=${HMAC_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - /app/node_modules
    networks:
      - network_sistema_todo
    env_file:
      - .env

  servidor-ca:
    build:
      context: ./servidor-ca
      dockerfile: Dockerfile
    command: python ca.py #adicionei isto pq mesmo com o dockerfile, não consegue ir buscar o ca.py
    ports:
      - "5000:5000"
    environment:
      - CA_PASSWORD=${CA_PASSWORD}
    volumes:
      - ./servidor-ca:/app
    networks:
      - network_sistema_todo
    env_file:
      - .env

  verify-server:
    build: 
      context: ./servidor-ca
      dockerfile: Dockerfile
    command: python criptografia/verify_cert.py
    ports:
      - "6060:6060"
    volumes:
      - ./servidor-ca:/app
    networks:
      - network_sistema_todo
    env_file:
      - .env
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - network_sistema_todo
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - app
    volumes:
     - ./certs:/etc/nginx/certs:ro
     - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
     - network_sistema_todo
    restart: unless-stopped
      
networks:
  network_sistema_todo:
    driver: bridge

volumes:
  mongo_data:
  
#Se precisarem, alterem o código !!
# ver aula de 7/05 e ver volums
